import type { AppDictionary } from "@/langs/types";

export const database: AppDictionary["database"] = {
  sectionTitle: "Bancos de Dados",
  newConnection: "Nova Conexão",
  connecting: "Conectando...",
  connected: "Conectado",
  disconnected: "Desconectado",
  errorConnecting: "Falha ao conectar",
  runQuery: "Executar Query",
  queryPlaceholder: "SELECT * FROM ...",
  noResults: "Sem resultados",
  rowCount: "linhas",
  durationMs: "ms",
  tabularMode: "Tabular",
  explorerMode: "Explorer",
  databases: "Bancos",
  schemas: "Schemas",
  tables: "Tabelas",
  views: "Views",
  columns: "Colunas",
  indexes: "Índices",
  foreignKeys: "Chaves Estrangeiras",
  ddl: "DDL",
  tableData: "Dados",
  browseData: "Ver Dados",
  describeTable: "Descrever Tabela",
  primaryKey: "Chave Primária",
  nullable: "Nulo",
  defaultValue: "Padrão",
  drawerTitle: "Nova Conexão de Banco",
  drawerTitleEdit: "Editar Conexão de Banco",
  fieldName: "Nome",
  fieldDriver: "Tipo de banco",
  fieldHost: "Host",
  fieldPort: "Porta",
  fieldUsername: "Usuário",
  fieldPassword: "Senha",
  fieldDatabase: "Nome do banco",
  fieldFilePath: "Caminho do arquivo",
  fieldSsl: "Usar SSL",
  testConnection: "Testar Conexão",
  testSuccess: "Conexão bem-sucedida",
  testError: "Falha na conexão",
  deleteConfirm: "Excluir esta conexão de banco?",
  affectedRows: "linhas afetadas",
  queryError: "Erro na query",
  loadingTree: "Carregando...",
  emptyDatabase: "Nenhuma tabela encontrada",
  retry: "Tentar novamente",
  close: "Fechar",
  disconnect: "Desconectar",
  selectTable: "Selecione uma tabela na árvore",
  tabData: "Dados",
  tabStructure: "Estrutura",
  tabSql: "SQL",
  tabProperties: "Propriedades",
  tabStatistics: "Estatísticas",
  tabDatabase: "Banco de dados",
  tabTable: "Tabela",
  tabBasic: "Básico",
  tabOptions: "Opções",
  tabCreate: "Código CREATE",
  tabAlter: "Código ALTER",
  colRows: "Registros",
  colSize: "Tamanho",
  colCreatedAt: "Criado em",
  colUpdatedAt: "Atualizado em",
  colEngine: "Motor",
  colComment: "Comentário",
  colVersion: "Versão",
  colRowFormat: "Formato do registro",
  colAvgRowLen: "Tamanho médio do registro",
  colMaxDataLen: "Tamanho máximo da linha",
  colIndexLen: "Tamanho do index",
  colDataFree: "Espaço livre",
  colAutoIncrement: "Auto-incremento",
  colCheckTime: "Tempo checado",
  colCollation: "Colação",
  colChecksum: "Checksum",
  colCreateOptions: "Opções de criação",
  colType: "Tipo",
  toggleColumns: "Alternar colunas",
  queryTab: "Consulta",
  newQuery: "Nova Consulta",
  toolbarCopy: "Copiar",
  toolbarPaste: "Colar",
  toolbarBack: "Voltar",
  toolbarPrint: "Imprimir",
  toolbarRefresh: "Atualizar",
  manageUsers: "Gerenciar Usuários",
  filterPlaceholder: "Filtrar...",
  editCellError: "Erro ao Atualizar",
  sectionSubtitle: "Gerencie suas conexões de banco de dados",
  searchPlaceholder: "Buscar conexões...",
  statsTotal: "Total",
  statsMysql: "MySQL / MariaDB",
  statsPostgres: "PostgreSQL",
  statsSqlite: "SQLite",
  statusIdle: "Ocioso",
  statusOpen: "Aberto",
};
