import type { AppDictionary } from "../types";

export const notes: AppDictionary["notes"] = {
  title: "Notas",
  subtitle: "Notas pessoais com cores e menções.",
  newNote: "Nova nota",
  searchPlaceholder: "Buscar notas...",
  emptyTitle: "Nenhuma nota ainda",
  emptyDescription: "Crie uma nota para guardar comandos, IPs, dicas de senha e muito mais.",
  addFirst: "Criar primeira nota",
  pinned: "Fixadas",
  all: "Todas as notas",
  pin: "Fixar",
  unpin: "Desafixar",
  edit: "Editar",
  remove: "Excluir",
  colorLabel: "Cor",
  titleLabel: "Título",
  titlePlaceholder: "Título da nota...",
  contentLabel: "Conteúdo",
  contentPlaceholder: "Escreva sua nota... Use @título para mencionar outra nota.",
  mentionHint: "Dica: digite @título para mencionar outra nota.",
  colors: {
    default: "Padrão",
    yellow: "Amarelo",
    blue: "Azul",
    green: "Verde",
    pink: "Rosa",
    purple: "Roxo",
    red: "Vermelho",
    orange: "Laranja",
    cyan: "Ciano",
  },
  drawer: {
    titleNew: "Nova nota",
    titleEdit: "Editar nota",
    description: "Preencha o conteúdo da nota e escolha uma cor de destaque.",
    cancel: "Cancelar",
    save: "Salvar",
  },
  deleteConfirmTitle: "Excluir nota",
  deleteConfirmMessage: 'Tem certeza que deseja excluir "{title}"?',
  deleteConfirmAction: "Excluir",
  statsTotal: "Total",
  statsPinned: "Fixadas",
  statsColored: "Coloridas",
  statsUpdatedToday: "Atualizadas hoje",
};
