[package]
name = "openptl"
version = "0.2.0"
edition = "2021"
description = "OpenPtl — cliente nativo de conexões SSH e SFTP"
license = "MIT"

[[bin]]
name = "openptl"
path = "src/main.rs"

[dependencies]
anyhow = "1"
argon2 = "0.5"
base64 = "0.22"
bincode = { version = "2", features = ["serde"] }
chacha20poly1305 = "0.10"
chrono = { version = "0.4", default-features = false, features = ["clock", "serde"] }
directories = "6"
eframe = "0.33"
open = "5"
rand = "0.8"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
russh = "0.52.0"
russh-sftp = "2.1.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tempfile = "3"
tokio = { version = "1", features = ["rt-multi-thread", "time", "net", "io-util", "macros", "sync", "fs"] }
urlencoding = "2"
uuid = { version = "1", features = ["v4", "serde"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
keyring = "2.3"

[profile.release]
strip = true
lto = true
opt-level = "s"
codegen-units = 1
