import type { AppDictionary } from "@/langs/types";

export const database: AppDictionary["database"] = {
  sectionTitle: "Databases",
  newConnection: "New Connection",
  connecting: "Connecting...",
  connected: "Connected",
  disconnected: "Disconnected",
  errorConnecting: "Failed to connect",
  runQuery: "Run Query",
  queryPlaceholder: "SELECT * FROM ...",
  noResults: "No results",
  rowCount: "rows",
  durationMs: "ms",
  tabularMode: "Tabular",
  explorerMode: "Explorer",
  databases: "Databases",
  schemas: "Schemas",
  tables: "Tables",
  views: "Views",
  columns: "Columns",
  indexes: "Indexes",
  foreignKeys: "Foreign Keys",
  ddl: "DDL",
  tableData: "Data",
  browseData: "Browse Data",
  describeTable: "Describe Table",
  primaryKey: "Primary Key",
  nullable: "Nullable",
  defaultValue: "Default",
  drawerTitle: "New Database Connection",
  drawerTitleEdit: "Edit Database Connection",
  fieldName: "Name",
  fieldDriver: "Database type",
  fieldHost: "Host",
  fieldPort: "Port",
  fieldUsername: "Username",
  fieldPassword: "Password",
  fieldDatabase: "Database name",
  fieldFilePath: "File path",
  fieldSsl: "Use SSL",
  testConnection: "Test Connection",
  testSuccess: "Connection successful",
  testError: "Connection failed",
  deleteConfirm: "Delete this database connection?",
  affectedRows: "affected rows",
  queryError: "Query error",
  loadingTree: "Loading...",
  emptyDatabase: "No tables found",
  retry: "Retry",
  close: "Close",
  disconnect: "Disconnect",
  selectTable: "Select a table from the tree",
  tabData: "Data",
  tabStructure: "Structure",
  tabSql: "SQL",
  tabProperties: "Properties",
  tabStatistics: "Statistics",
  tabDatabase: "Database",
  tabTable: "Table",
  tabBasic: "Basic",
  tabOptions: "Options",
  tabCreate: "CREATE Code",
  tabAlter: "ALTER Code",
  colRows: "Rows",
  colSize: "Size",
  colCreatedAt: "Created at",
  colUpdatedAt: "Updated at",
  colEngine: "Engine",
  colComment: "Comment",
  colVersion: "Version",
  colRowFormat: "Row format",
  colAvgRowLen: "Avg row length",
  colMaxDataLen: "Max row size",
  colIndexLen: "Index size",
  colDataFree: "Free space",
  colAutoIncrement: "Auto increment",
  colCheckTime: "Check time",
  colCollation: "Collation",
  colChecksum: "Checksum",
  colCreateOptions: "Create options",
  colType: "Type",
  toggleColumns: "Toggle columns",
  queryTab: "Query",
  newQuery: "New Query",
  toolbarCopy: "Copy",
  toolbarPaste: "Paste",
  toolbarBack: "Back",
  toolbarPrint: "Print",
  toolbarRefresh: "Refresh",
  manageUsers: "Manage Users",
  filterPlaceholder: "Filter...",
  editCellError: "Update Error",
  sectionSubtitle: "Manage your database connections",
  searchPlaceholder: "Search connections...",
  statsTotal: "Total",
  statsMysql: "MySQL / MariaDB",
  statsPostgres: "PostgreSQL",
  statsSqlite: "SQLite",
  statusIdle: "Idle",
  statusOpen: "Open",
};
