import type { AppDictionary } from "../types";

export const notes: AppDictionary["notes"] = {
  title: "Notes",
  subtitle: "Personal notes with colors and mentions.",
  newNote: "New note",
  searchPlaceholder: "Search notes...",
  emptyTitle: "No notes yet",
  emptyDescription: "Create a note to keep track of commands, IPs, passwords hints, and more.",
  addFirst: "Create first note",
  pinned: "Pinned",
  all: "All notes",
  pin: "Pin",
  unpin: "Unpin",
  edit: "Edit",
  remove: "Delete",
  colorLabel: "Color",
  titleLabel: "Title",
  titlePlaceholder: "Note title...",
  contentLabel: "Content",
  contentPlaceholder: "Write your note... Use @title to mention another note.",
  mentionHint: "Tip: type @title to mention another note inline.",
  colors: {
    default: "Default",
    yellow: "Yellow",
    blue: "Blue",
    green: "Green",
    pink: "Pink",
    purple: "Purple",
    red: "Red",
    orange: "Orange",
    cyan: "Cyan",
  },
  drawer: {
    titleNew: "New note",
    titleEdit: "Edit note",
    description: "Fill in the note content and choose a highlight color.",
    cancel: "Cancel",
    save: "Save",
  },
  deleteConfirmTitle: "Delete note",
  deleteConfirmMessage: 'Are you sure you want to delete "{title}"?',
  deleteConfirmAction: "Delete",
};
