import type { AppDictionary } from "../types";

export const workspace: AppDictionary["workspace"] = {
  tabTitle: "Workspace",
  modeFree: "Free",
  modeGrid: "Grid",
  addBlock: "New Block",
  newBlockTitle: "New Block",
  newBlockDescription: "Choose which block to open in this workspace.",
  createLocalTitle: "Local",
  createRemoteTitle: "Remote Connections",
  localTerminal: "Local Terminal",
  localSftp: "Local SFTP",
  localEditor: "Local Editor",
  remoteTerminal: "Remote Terminal",
  remoteFiles: "Remote Files",
  sourceLabel: "Connection",
  sourceHelpTerminal: "Choose an SSH connection to open a remote terminal.",
  sourceHelpFiles: "Choose a remote connection to open files (SFTP).",
  accessConnection: "Access Connection",
  selectConnectionTitle: "Open Connection",
  selectConnectionDescription: "Select a saved connection to open in this workspace.",
  selectConnectionSearchPlaceholder: "Search connection...",
  selectConnectionEmpty: "No connection found.",
  blockSftp: "SFTP Block",
  blockTerminal: "Terminal Block",
  allMinimizedHint: "All blocks are minimized. Use the top bar to restore one.",
  transfer: "transfer(s)",
  transferFolder: "Folder transfer is still in rollout. Move files for now.",
  transferSuccess: "Transferred to {destination}",
  closeTitle: "Close workspace",
  closeMessage: 'Do you really want to close "{title}"? This will end associated sessions.',
  closing: "Closing...",
  closeConfirm: "Close Workspace",
  captureDisabledGeneric: "Native keyboard/mouse capture is currently unavailable.",
  captureDisabledWayland: "Global capture on Linux does not support Wayland in this phase (use X11).",
  captureDisabledPermission: "Accessibility permission is missing. Allow the app to capture input.",
};
