export global Type {
    out property <length> display: 22px;
    out property <length> title: 17px;
    out property <length> body: 13px;
    out property <length> label: 12px;
    out property <length> caption: 11px;

    out property <int> weight-regular: 400;
    out property <int> weight-medium: 500;
    out property <int> weight-bold: 700;

    out property <string> mono-family: "Consolas";
}
